export const SOLUTIONS = [
    {
        id: 0,
        timeAmt: "fiveMin",
        name: "Breathe",
        description: "Do a deep breathing exercise.",
        link: "https://www.webmd.com/balance/stress-management/stress-relief-breathing-techniques",
        linkDescription: "'Breathing Techniques for Stress Relief' on WebMD",
        show: true,
    },
    {
        id: 1,
        timeAmt: "fiveMin",
        name: "Stretch",
        description: "Reach high! Reach your toes!",
        link: "https://www.healthline.com/health/fitness-exercise/daily-stretching-routine",
        linkDescription: "",
        show: true,
    },
    {
        id: 2,
        timeAmt: "fiveMin",
        name: "5 push-ups",
        description: "Do just 5 push-ups, focus on form.",
        link: "https://www.nerdfitness.com/blog/proper-push-up/",
        linkDescription: "",
        show: true,
    },
    {
        id: 3,
        timeAmt: "fiveMin",
        name: "Apply mascara",
        description: "A few quick swipes to showcase your eyes. Beautiful!",
        link: "https://www.youtube.com/watch?v=tQ1FyKKO0oo",
        linkDescription: "",
        show: true,
    },
    {
        id: 4,
        timeAmt: "fiveMin",
        name: "Tidy a counter",
        description:
            "Put things where they go, or in a tidy pile to sort later. The goal is just to make it a little bit tidier, not completely clean!",
        link: "https://www.unfuckyourhabitat.com/",
        linkDescription: "",
        show: true,
    },
    {
        id: 5,
        timeAmt: "fiveMin",
        name: "Toss trash",
        description:
            "Throw away any trash you can see. Only for the time you have, though!",
        link: "https://www.unfuckyourhabitat.com/",
        linkDescription: "",
        show: true,
    },
    {
        id: 6,
        timeAmt: "fiveMin",
        name: "Text someone",
        description:
            "Someone you haven't talked to in a while. They'd love to hear from you.",
        link: "https://cmha.ca/the-importance-of-human-connection/#:~:text=Social%20connection%20can%20lower%20anxiety,a%20time%20of%20true%20disconnection.",
        linkDescription: "",
        show: true,
    },
    {
        id: 7,
        timeAmt: "fiveMin",
        name: "Check your to-do's",
        description:
            "See what you still need to do. If it's too long, find the top 2 priorities for your day. If you don't have a list, make one!",
        link: "https://todoist.com/",
        linkDescription: "",
        show: true,
    },
    {
        id: 8,
        timeAmt: "fiveMin",
        name: "Sew a button",
        description:
            "It just takes a few minutes, then you don't have to worry about it again.",
        link: "https://www.youtube.com/watch?v=MmcEF2GR584",
        linkDescription: "",
        show: true,
    },
    {
        id: 9,
        timeAmt: "fiveMin",
        name: "Check bills",
        description:
            "Have you paid them for this statement period? When are they due next?",
        link: "https://www.printabulls.com/finance/monthly-bill-organizers/",
        linkDescription: "",
        show: true,
    },
    {
        id: 10,
        timeAmt: "fiveMin",
        name: "ID a tree",
        description:
            "Check the leaf shape and the bark pattern. Are there flowers or other unique parts of the plant?",
        link: "https://www.arborday.org/trees/whattree/",
        linkDescription: "",
        show: true,
    },
    {
        id: 11,
        timeAmt: "fiveMin",
        name: "Water plants",
        description:
            "Check to be sure they need the water, first! Usually a plant will need water when the soil is dry up to your first kuckle when you put a finger into the soil. If you have more than you have time for, try to water plants by area and then note which areas still need water.",
        link: "https://www.bobvila.com/articles/watering-plants/#:~:text=How%20often%20should%20plants%20be,soil%20beneath%20should%20remain%20moist.",
        linkDescription: "",
        show: true,
    },
    {
        id: 12,
        timeAmt: "tenMin",
        name: "Practice a language",
        description: "If you're not already, pick up one to start!",
        link: "https://play.google.com/store/apps/details?id=com.duolingo&hl=en_US&gl=US",
        linkDescription: "",
        show: true,
    },
    {
        id: 13,
        timeAmt: "tenMin",
        name: "Clean a counter",
        description:
            "Put things in their places if they live in that room, or in a basket to go to another room. Wipe down the counter. If you have time, take the basket to another room where the contents live.",
        link: "https://www.unfuckyourhabitat.com/",
        linkDescription: "",
        show: true,
    },
    {
        id: 14,
        timeAmt: "tenMin",
        name: "Do yoga",
        description:
            "A few small poses to stretch out and breathe. If you're in an office, do some chair yoga.",
        link: "https://health.clevelandclinic.org/12-yoga-poses-can-work/",
        linkDescription: "",
        show: true,
    },
    {
        id: 15,
        timeAmt: "tenMin",
        name: "Google something",
        description:
            "Think of something you wondered about before now. Go google that and find out an answer. Can't think of something? Try Wikipedia's random pages.",
        link: "https://en.wikipedia.org/wiki/Special:Random",
        linkDescription: "",
        show: true,
    },
    {
        id: 16,
        timeAmt: "tenMin",
        name: "Brush your hair",
        description:
            "How soothing! No hair, no hairbrush, or hard to brush hair? Go find hand lotion and moisturize! Take care of yourself!",
        link: "https://www.healthline.com/health/brushing-hair#benefits-of-brushing",
        linkDescription: "",
        show: true,
    },
    {
        id: 17,
        timeAmt: "tenMin",
        name: "Make your bed",
        description:
            "It's an easy win! Not at home, or someone still in your bed? Organize a surface (desk, counter, etc.) so you have some visible clear space. This doesn't have to be perfect, good enough is awesome!",
        link: "https://www.unfuckyourhabitat.com/",
        linkDescription: "",
        show: true,
    },
    {
        id: 18,
        timeAmt: "tenMin",
        name: "Take a walk",
        description:
            "Just a short one, around your house or around the office. Extra great if you can walk outside.",
        link: "",
        linkDescription: "",
        show: true,
    },
    {
        id: 19,
        timeAmt: "tenMin",
        name: "Start a book",
        description:
            "You don't even have to read for long, just a few minutes. Don't have a book handy? Open Library has plenty of free books available online.",
        link: "https://openlibrary.org/",
        linkDescription: "",
        show: true,
    },
    {
        id: 20,
        timeAmt: "tenMin",
        name: "ID a birdcall",
        description: "Find out what species that neat bird outside is!",
        link: "https://merlin.allaboutbirds.org/",
        linkDescription: "",
        show: true,
    },
    {
        id: 21,
        timeAmt: "tenMin",
        name: "Draw something",
        description:
            "Just a little doodle, of something you see or something you're thinking about. No ideas? Try a drawing prompt!",
        link: "https://onedoodleaday.tumblr.com/",
        linkDescription: "",
        show: true,
    },
    {
        id: 22,
        timeAmt: "fifteenMin",
        name: "Take a walk outside",
        description:
            "Take a walk around the block, or around the office complex! Make it a little brisk if you can, a little cardio every day improves your health dramatically, and being outside is a nice change of scenery for most of us!",
        link: "https://www.bbc.com/news/health-14526853",
        linkDescription: "",
        show: true,
    },
    {
        id: 23,
        timeAmt: "fifteenMin",
        name: "Mend something simple",
        description:
            "Have a household item that needs a quick bit of tape, a kid's toy that needs some hot glue, or a belt loop that needs a few stiches? This could be your chance!",
        link: "https://lifehacker.com/five-basic-hand-stitches-you-should-know-for-repairing-1723233194",
        show: true,
    },
    {
        id: 24,
        timeAmt: "fifteenMin",
        name: "Braid your hair",
        description:
            "A simple braid if youre new to it, or find an interesting new braid if you're quick at the usuals!",
        link: "https://www.youtube.com/watch?v=p4VaL-AG7cI",
        show: true,
    },
    {
        id: 25,
        timeAmt: "twentyMin",
        name: "Study something",
        description:
            "You probably have something you'd like to learn how to be better at. Maybe study your target language, or practice a piece of music on an instrument. If you're a student, find a topic you struggle with in a subject you like. If you're not a student, research something related to your job, or learn something to get you the job you want. Above all, make this something you enjoy, it's not a punishment!",
        link: "https://www.sciencenewsforstudents.org/article/top-10-tips-study-smarter-not-longer-study-skills",
        show: true,
    },
    {
        id: 26,
        timeAmt: "thirtyMin",
        name: "Mend something",
        description: "Sew a hole in your pants! Darn a socks!",
        link: "https://www.youtube.com/watch?v=QR5q5OIG51A",
        show: true,
    },
    {
        id: 27,
        timeAmt: "thirtyMin",
        name: "Learn a skill",
        description:
            "Learn to juggle! Or learn to yoyo, or to start a campfire! Learn how to survive a shark attack!",
        link: "https://www.mentalfloss.com/article/572087/learn-skills-on-youtube",
        show: true,
    },
    {
        id: 28,
        timeAmt: "thirtyMin",
        name: "Journal",
        description:
            "Write your thoughts and experiences for the day, your goals for yourself, you habits, or anything you'd like. Journalling helps you reflect on what you've done and plan to do it better.",
        link: "https://www.betterup.com/blog/how-to-start-journaling",
        show: true,
    },
    {
        id: 29,
        timeAmt: "thirtyMin",
        name: "Work on a crossword puzzle",
        description: "",
        link: "https://puzzles.usatoday.com/game/79742842-b902-47c4-b525-d3a91a7952b1",
        show: true,
    },
];
